

Drop INDEX basal_user_id_time_idx;
Drop INDEX basal_internal_mongo_id_idx;
Drop INDEX blood_ketone_user_id_time_idx;
Drop INDEX blood_ketone_internal_mongo_id_idx;
Drop INDEX bolus_user_id_time_idx;
Drop INDEX bolus_internal_mongo_id_idx;
Drop INDEX cbg_user_id_time_value_idx;
Drop INDEX cbg_internal_mongo_id_idx;
Drop INDEX cgm_settings_user_id_time_idx;
Drop INDEX cgm_settings_internal_mongo_id_idx;
Drop INDEX device_event_user_id_time_idx;
Drop INDEX device_event_internal_mongo_id_idx;
Drop INDEX device_meta_user_id_time_idx;
Drop INDEX device_meta_internal_mongo_id_idx;
Drop INDEX dosing_decision_user_id_time_idx;
Drop INDEX dosing_decision_internal_mongo_id_idx;
Drop INDEX food_user_id_time_idx;
Drop INDEX food_internal_mongo_id_idx;
Drop INDEX insulin_user_id_time_idx;
Drop INDEX insulin_internal_mongo_id_idx;
Drop INDEX physical_activity_user_id_time_idx;
Drop INDEX physical_activity_internal_mongo_id_idx;
Drop INDEX pump_settings_user_id_time_idx;
Drop INDEX pump_settings_internal_mongo_id_idx;
Drop INDEX reported_state_user_id_time_idx;
Drop INDEX reported_state_internal_mongo_id_idx;
Drop INDEX settings_user_id_time_idx;
Drop INDEX settings_internal_mongo_id_idx;
Drop INDEX smbg_user_id_time_idx;
Drop INDEX smbg_internal_mongo_id_idx;
Drop INDEX upload_user_id_time_idx;
Drop INDEX upload_internal_mongo_id_idx;
Drop INDEX wizard_user_id_time_idx;
Drop INDEX wizard_internal_mongo_id_idx;

